explicitly disable libxmlsec1 dynamic loading
without this, the samael crate will not build due to cannot find
function errors like this:

    error[E0425]: cannot find function `xmlSecOpenSSLShutdown` in module `bindings`
         --> src/xmlsec/xmlsec.rs:98:24
          |
    98    |     unsafe { bindings::xmlSecOpenSSLShutdown() };
          |                        ^^^^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `xmlSecCryptoDLShutdown`
          |
         ::: /home/james/samael/target/debug/build/samael-43f9c90eb34cdf2d/out/bindings.rs:23953:5
          |
    23953 |     pub fn xmlSecCryptoDLShutdown() -> ::std::os::raw::c_int;
          |     --------------------------------------------------------- similarly named function `xmlSecCryptoDLShutdown` defined here

The xmlsec code supports dynamic loading and provides indirection with
defines and function pointers:

    src/openssl/crypto.c
    66:    gXmlSecOpenSSLFunctions->cryptoShutdown             = xmlSecOpenSSLShutdown;
    352: * xmlSecOpenSSLShutdown:
    359:xmlSecOpenSSLShutdown(void) {

    include/xmlsec/openssl/symbols.h
    28:#define xmlSecCryptoShutdown                    xmlSecOpenSSLShutdown

    include/xmlsec/openssl/crypto.h
    49:XMLSEC_CRYPTO_EXPORT int                xmlSecOpenSSLShutdown           (void);

Turn all this off, the samael crate references the openssl functions
directly.

Also, put a short blob in the README about testing.